plugins/modules/turbo_demo.py
Add an example of a plugin based on ansible_module.turbo.
=> add a demo plugin

plugins/module_utils/turbo/module.py
We now install the socket in `~/ansible/tmp`.
=> Use the host local temp directory

README_ansible_turbo.module.rst
Depends-On: https://github.com/ansible-collections/cloud.common/pull/5
=> add a note about exception managment

README_ansible_turbo.module.rst, plugins/module_utils/turbo/module.py, plugins/module_utils/turbo/server.py, plugins/modules/turbo_demo.py
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
README_ansible_turbo.module.rst
plugins/module_utils/turbo/module.py
plugins/module_utils/turbo/server.py
plugins/modules/turbo_demo.py
=> Update README docs

README_ansible_turbo.module.rst
Add a section to document the security impact of the cache.
Closes: #14
=> doc: add a security section

changelogs/fragments/improve-the-demo-module_5397.yaml, plugins/modules/turbo_demo.py, tests/integration/targets/turbo_mode/playbook.yaml, tests/integration/targets/turbo_mode/runme.sh, tests/integration/targets/turbo_mode/tasks/main.yaml
- add a functional test
- return the counter in the output
Signed-off-by: Gonéri Le Bouder <goneri@lebouder.net>
=> improve the demo module

changelogs/fragments/fork_mode_print_information_about_the_module.yaml, plugins/module_utils/turbo/server.py, tests/sanity/ignore-2.10.txt
Print some information about the module in the terminal when the
user starts the background process manually.
=> fork mode: print information about the module

plugins/module_utils/turbo/module.py
Fetch 1Mb per loop and add a time to reduce potential CPU cycle.
=> reduce the nbr of loops to retrieve the daemon output

changelogs/fragments/fork_mode_print_information_about_the_module.yaml, changelogs/fragments/raise_exception_if_output_parsing_fails.yaml
Depends-On: https://github.com/ansible-collections/cloud.common/pull/40
=> changelog: add some missing entries

changelogs/fragments/filter_argument_with_argument_spec.yaml, plugins/module_utils/turbo/module.py
Use the argument_spec values to determine which option should actually be used.
=> use argument_spec to build the argument dict

plugins/module_utils/turbo/server.py
Depends-On: https://github.com/ansible-collections/cloud.common/pull/48
=> add py3.10 fix for start_unix_server

changelogs/fragments/modulefailure_fix_result.yaml, plugins/module_utils/turbo/exceptions.py, plugins/module_utils/turbo/server.py, plugins/modules/turbo_fail.py, tests/integration/targets/turbo_fail/tasks/main.yaml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Depends-On: https://github.com/ansible-collections/cloud.common/pull/57
Depends-On: https://github.com/ansible-collections/vmware.vmware_rest/pull/207
closes #55 
EmbeddedModuleFailure
=> EmbeddedModuleFailure - Honor kwargs

changelogs/fragments/py3.10-fix.yaml
Introduces a fix for the future Python 3.10 (#53)
=> add a changelog fragment

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/actually_enable_the_profiler.yaml, changelogs/fragments/filter_argument_with_argument_spec.yaml, changelogs/fragments/modulefailure_fix_result.yaml
Depends-On: https://github.com/ansible-collections/cloud.common/pull/59
=> prepare 2.0.2 release

README_ansible_turbo.module.rst
misc fixes
README_ansible_turbo.module.rst
=> Add kubernetes reference

README.md
Depends-On: https://github.com/ansible-collections/vmware.vmware_rest/pull/235
Some docs updates for https://github.com/ansible-collections/ansible-inclusion/discussions/30
README.md
=> README updates for community package inclusion

changelogs/fragments/102-lookup-add-support-for-coroutine.yaml, changelogs/fragments/75-lookup-add-support-for-coroutine.yaml, plugins/lookup/turbo_demo.py, plugins/module_utils/turbo/server.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt
Turbo mode for lookup plugins should support coroutine
=> [turbo] lookup support coroutine

plugins/module_utils/turbo/module.py, tests/unit/module_utils/test_turbo_module.py
The generation of the final parameter structure is slightly complicated.
This commit breaks the _prepare_args() method in two and adds test coverage.
=> tests: cover the module params generation

plugins/module_utils/turbo/common.py, plugins/module_utils/turbo/exceptions.py, plugins/module_utils/turbo/module.py, plugins/module_utils/turbo/server.py, plugins/plugin_utils/turbo/lookup.py
Add the BSD headers to the files from plugins/module_utils and
plugins/plugin_utils.
See: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#licensing
=> Add BSD headers to the plugins/*_utils files

changelogs/fragments/cosmetic_changes.yaml
Add some missing changelog entries.
=> changelog: covers some changes since 2.0.4

tests/integration/targets/turbo_lookup/playbook.yaml
Depends-On: https://github.com/ansible-collections/cloud.common/pull/110
=> tests: clean up some trailing white spaces

plugins/module_utils/turbo/server.py
See: https://github.com/ansible-collections/cloud.common/pull/109#discussion_r905251586
=> turbo: ensure we clean up the leaked jobs

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/improvements.yml, changelogs/fragments/pin_black_version.yml, changelogs/fragments/update_booleans.yml
Prep 2.1.3 release
```paste below
```
=> Prep 2.1.3 release

.github/workflows/tests.yml, changelogs/fragments/gh-workflow.yaml, galaxy.yml, plugins/module_utils/turbo/server.py, plugins/modules/turbo_fail.py, pytest.ini, test-requirements.txt, tests/unit/plugins/module_utils/turbo/test_turbo_module.py
This PR adds linters, sanity, changelog and unit test workflows for this repo.
```paste below
```
=> Add GitHub Action workflows for CI

.github/workflows/changelog.yml, .github/workflows/linters.yml, .github/workflows/sanity_and_units.yml, .github/workflows/tests.yml, .github/workflows/unit-ansible-2.9.yml, tests/sanity/ignore-2.16.txt
- sanity: add `ansible_version=devel, python_version=3.9` from exclude matrix
- unit tests: Remove dependency installation
- add new trigger to run periodically sanity and unit tests jobs as it was done on zuul
CI
=> CI Fixes: sanity and unit tests

README.md, changelogs/fragments/update_ansible_version.yml, meta/runtime.yml
=> Update README.md and meta/runtime.yml to reflect our ansible core testing versions

.github/workflows/sanity_and_units.yml
Exclude python 3.9 from milestone testing
```paste below
```
=> Exclude python 3.9 from milestone testing

.github/workflows/sanity_and_units.yml
=> Exclude python 3.9 from milestone unit testing

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/130-fix-ansible-2.15.yml, changelogs/fragments/20230726-lookup.yml, changelogs/fragments/gh-workflow.yaml, changelogs/fragments/update_ansible_version.yml, galaxy.yml
Prep cloud.common 2.1.4
```paste below
```
=> Prep cloud.common 2.1.4

README.md, changelogs/fragments/increase_ansible_core_version.yml, meta/runtime.yml, tests/sanity/ignore-2.18.txt
Drop support for ansible-core < 2.15.
```paste below
```
=> Drop support for ansible-core < 2.15

tests/sanity/ignore-2.18.txt
Add tests/sanity/ignore-2.18.txt
```paste below
```
=> Add tests/sanity/ignore-2.18.txt

CI.md, README.md
Update doc links after branching stable-3
```paste below
```
=> Update doc links after branching stable-3

CI.md, README.md
Update docs links after branching stable-4
```paste below
```
=> Update docs links after branching stable-4

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/20240103-module_utils-turbo-server-import-fix.yaml.yaml, changelogs/fragments/increase_ansible_core_version.yml, galaxy.yml
Prep cloud.common 4.0.0 release. 
```paste below
```
=> Prep cloud.common 4.0.0 release

galaxy.yml
Update version to reflect the next major release version
```paste below
```
=> Update version to reflect the next major release version

CHANGELOG.rst, changelogs/changelog.yaml
=> Fix typo in CHANGELOG.rst  and changelogs/changelog.yaml

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/20240103-module_utils-turbo-server-import-fix.yaml.yaml, changelogs/fragments/increase_ansible_core_version.yml
Changelog update. after releasing 4.0.0
```paste below
```
=> Changelog update. after releasing 4.0.0

.github/workflows/linters.yaml, changelogs/fragments/170-update-ansible-lint-version.yml
Bump ansible-lint version to 25.1.2
=> Update ansible-lint to 25.1.2

.github/workflows/linters.yaml, changelogs/fragments/170-update-ansible-lint-version.yml
=> Undo updates

.github/workflows/linters.yaml, changelogs/fragments/170-update-ansible-lint-version.yml
Update ansible-lint to 25.1.2
Manual Backport of #170 
```paste below
```
=> [Manual Backport][Stable-4]Update ansible-lint to 25.1.2

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/160-add-ansible-2.19-support.yml, changelogs/fragments/170-update-ansible-lint-version.yml, galaxy.yml
=> Prep cloud.common release 4.1.0

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/160-add-ansible-2.19-support.yml, changelogs/fragments/170-update-ansible-lint-version.yml
SUMMARY
cherry pick #176 
ISSUE TYPE
Bugfix Pull Request
Docs Pull Request
Feature Pull Request
New Module Pull Request
COMPONENT NAME
ADDITIONAL INFORMATION
Reviewed-by: Alina Buzachis
Reviewed-by: Bianca Henderson <beeankha@gmail.com>
(cherry picked from commit 676854532362c1709d0b30c66f489327365b1479)
```paste below
```
=> Sync release 4.1.0  into main

.github/workflows/integration-tests-kubernetes-core.yaml
Update Python testing matrix.
Add versions `3.9`, `3.10`, and `3.11`
=> Update Python matrix for integration tests

CHANGELOG.rst, README.md, changelogs/changelog.yaml, changelogs/fragments/0-readme.yml, changelogs/fragments/159-bump-ansible-lint-version.yml, changelogs/fragments/183-update-supported-ansible-versions.yml, changelogs/fragments/readme_template_update.yml, galaxy.yml
Prepare release `5.0.0`
- Generate release changelog
- Update `galaxy.yml`
- Release Pull Request
=> Prepare release 5.0.0

CHANGELOG.rst, README.md, changelogs/changelog.yaml, changelogs/fragments/0-readme.yml, changelogs/fragments/159-bump-ansible-lint-version.yml, changelogs/fragments/183-update-supported-ansible-versions.yml, changelogs/fragments/readme_template_update.yml, galaxy.yml
Release `5.0.0` is out. This pull request updates the main branch to reflect the changes handled in that release.
=> Push 5.0.0 to main
