plugins/module_utils/turbo/exceptions.py
plugins/module_utils/turbo/module.py
plugins/module_utils/turbo/server.py

`EmbeddedModuleFailure` accepts now a `msg` key. This way, we
can directly pass `json_fail` arguments when we raise an exception.

correctly json_fail's msg key when raising an exption

---

plugins/module_utils/turbo/module.py

We don't pass the raw parameters to the server, instead we reuse
the parameters that have been generated by the local `_load_params()`.
This way we are sure we won't fallback on `env_fallback`, with the
potential security complication.

module -> server: pass the proceeded params

---

plugins/module_utils/turbo/server.py

This change address a problem on MacOS.
If we create the asyncio lock before we do the double forks, it
actually initialize the asyncio context in the father process. And later
we get an "Bad file descriptor" when we try to start the asyncio endless
loop in the child process.
See: https://python-tornado.narkive.com/a9lCRPxp/errno-9-bad-file-descriptor#post2
Closes: #13

Initialize sys_path_lock after the double fork()

---

changelogs/fragments/dont_ignore_parameters_when_val_is_False.yaml
plugins/module_utils/turbo/module.py

A parameter with a `False` value can be a legit parameter that we want
to pass to the module.
See: https://github.com/ansible-collections/vmware.vmware_rest/issues/154

don't ignore parameter if value == False

---

README_ansible_turbo.module.rst

- Use `background service` terminology, instead of `daemon`
- Add a Troubleshooting section.

extend the documentation

---

README_ansible_turbo.module.rst

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/684
Follow up to 24823345fbf4976b64e09775a01e627c84c4ddac, the socket
name now includes the name of the collection.

turbo_mode/doc: adjust the path of the socket

---

changelogs/fragments/raise-an-error-if-exit_json-or-fail_json-not-called_13453.yaml
plugins/module_utils/turbo/server.py

`exit_json()` or `fail_json()` should always be called at the end of a
module execution. Since `ansible_module.turbo` relies on this to collect
the result, we now return a message if it's not the case.

raise an error if exit_json or fail_json not called

---

changelogs/fragments/fail_json_accept_extra_kwargs.yaml
plugins/module_utils/turbo/exceptions.py

Get `**kwargs` from `fail_json()` and pass the list to `EmbeddedModuleFailure` the
exception.

Ensure fail_json() accepts **kwargs

---

plugins/module_utils/turbo/module.py

Raise an exception when we cannot parse the answer of the daemon.

raise an exc is the output cannot be parsed

---

changelogs/fragments/get_the_collection_name_from_an_attribute.yaml
plugins/module_utils/turbo/module.py
plugins/modules/turbo_demo.py

Use an attribute to know the name of the collection. The goal
is to phase out `get_collection_name_from_path()` later.

get the collection name from an attribute

---

changelogs/fragments/argument_spec_server_side.yaml
plugins/module_utils/turbo/module.py

Depends-On: https://github.com/ansible-collections/cloud.common/pull/40
Delegate the argument validation to the server.

run the argument_spec server side

---

plugins/module_utils/turbo/server.py

Ensure we enable the profile before we use it or we will trigger
an error with Python 3.9.

debug: enable the profiler instance

---

changelogs/fragments/46-fix-error-message-string.yaml
plugins/module_utils/turbo/exceptions.py

This causes all the error messages to be surrounded in single quotes.
Instead, `__repr__` should return repr() and `__str__` should return str().
```paste below
```

Don't run exception message through repr()

---

tests/sanity/ignore-2.12.txt

Depends-On: https://github.com/ansible-collections/cloud.common/pull/48
This to avoid the following errors:
```
ERROR: Found 5 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.12.txt:30:1: Sanity test 'compile-2.6' does not test path 'tests/unit/module_utils/test_turbo_module.py'
ERROR: tests/sanity/ignore-2.12.txt:31:1: Sanity test 'compile-2.7' does not test path 'tests/unit/module_utils/test_turbo_module.py'
ERROR: tests/sanity/ignore-2.12.txt:32:1: Sanity test 'compile-3.5' does not test path 'tests/unit/module_utils/test_turbo_module.py'
ERROR: tests/sanity/ignore-2.12.txt:33:1: Sanity test 'future-import-boilerplate' does not test path 'tests/unit/module_utils/test_turbo_module.py'
ERROR: tests/sanity/ignore-2.12.txt:34:1: Sanity test 'metaclass-boilerplate' …
```

ignore-2.12: do not ignore test_turbo_module.py

---

changelogs/fragments/socket-closure-fix.yaml
plugins/module_utils/turbo/module.py
plugins/module_utils/turbo/server.py

AnsibleTurboModule had some bugs that manifested when large input data
were sent over the socket (greater than the hardcoded limit of 102400
bytes). This is uncommon, but in particular the kubernetes.core.k8s
module sends relatively large amounts of data as module arguments over
the socket connection, which triggers this bug.
The server was reading, at most, 102400 bytes of data. asyncio's
StreamReader.read(), with no arguments, will read until the End of File
is reached, so we add the `socket.shutdown` call to the client to send
an EOF. This closes the socket for writing, which is fine, since at this
point, all remaining communication flows from server to client.
Additionally, `socket.sendall` replaces `socket.send`, which does not
guarantee the whole message will be sent in one attempt: …

Fix premature socket closure

---

changelogs/fragments/reading-common-variable.yaml
plugins/module_utils/turbo/module.py
plugins/modules/turbo_demo.py
tests/integration/targets/turbo_mode/tasks/main.yaml

``PASS_VARS`` is dict with each data item defined as a 2-tuple with first item corresponding to the attribute to the AnsibleModule class.
Consequently, only the ``check_mode`` was copied as this is the only variable with the same name on both the tuple and the ``PASS_VARS`` key.

AnsibleTurboModule does transfer all AnsibleModule variable to the socket

---

changelogs/fragments/67-add-exception-handler.yaml
plugins/module_utils/turbo/server.py

The async loop had no exception handler attached besides the default.
This would cause the server to hang when an unhandled exception
occurred.
```paste below
```

Add exception handler for loop

---

README_ansible_turbo.module.rst

Small doc fix turbo module. I guess it should be `async` instead of `sync`.

Doc fix turbo module

---

changelogs/fragments/Respect_the_remote_tmp_setting.yaml
plugins/module_utils/turbo/module.py
tests/integration/targets/turbo_mode/tasks/main.yaml

This PR makes the turbo module respect custom remote Ansible temporary directories set by the `remote_tmp` setting in `ansible.cfg` or by the `ANSIBLE_REMOTE_TMP` environment variable.
This is necessary because in its current state the module will always try to create a socket in the default `$HOME/.ansible/tmp` temporary directory which may be missing if a custom `remote_tmp` is set.

Respect the remote_tmp setting

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/67-add-exception-handler.yaml
changelogs/fragments/69-pass-envvar.yaml
changelogs/fragments/Respect_the_remote_tmp_setting.yaml
changelogs/fragments/reading-common-variable.yaml
changelogs/fragments/turbo-for-lookup-plugin.yaml

Major Changes
-------------
- turbo - enable turbo mode for lookup plugins
Bugfixes
--------
- add exception handler to main async loop (https://github.com/ansible-collections/cloud.common/pull/67).
- pass current task's environment through to execution (https://github.com/ansible-collections/cloud.common/pull/69).
- turbo - AnsibleTurboModule was missing some _ansible_facts variable like _diff, _ansible_tmpdir. (https://github.com/ansible-collections/cloud.common/issues/65)
- turbo - honor the ``remote_tmp`` configuration key.

prepare 2.0.4 release

---

plugins/module_utils/turbo/module.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.9.txt
tests/unit/plugins/module_utils/turbo/conftest.py
tests/unit/plugins/module_utils/turbo/test_module.py

Turbo modules rely on core Ansible mechanism for temporary path creation on the target host. This means that the socket path calculation must be in sync with the core calculation.
Up until now, turbo modules only handled one happy path: where remote tmp location was set, it did not include any environment variables that would need to be expanded, and it did not have a trailing slash.
This commit brings the core and turbo modules in sync when it comes to remote temporary location calculations and adds a few tests to make sure things work as expected.
Fixes https://github.com/ansible-collections/vmware.vmware_rest/issues/262
AnsibleTurboModule

Update socket location calculation

---

changelogs/fragments/102-fix-incorrect-module-loading.yaml
plugins/module_utils/turbo/server.py
plugins/module_utils/turbo_demo.py
plugins/modules/turbo_demo.py
plugins/modules/turbo_import.py
tests/integration/targets/turbo_mode/tasks/main.yaml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.9.txt

There is currently a bug in the import logic that manifests when two
Ansible modules try to load a python module from somewhere in
module_utils. If the python module shares the same name as the second
(or subsequent) Ansible modules, turbo mode will attempt to load the
python module instead of the Ansible module.
This fixes the logic by removing the meta_path modification, which was
the root of the problem. Instead, it keeps the sys.path modification as
before, but attempts to reload any ansible_collection package modules.
We can't reload every module as this would overwrite any shared state in
the module cache, defeating the whole purpose of turbo mode. By
reloading only the package modules we force it to reexamine its
contents, which should now be pointing to the new zip archive since …

Fix import logic trying to load incorrect module

---

plugins/lookup/turbo_demo.py
plugins/modules/turbo_import.py

Depends-On: Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1578

sanity test: adjust turbo_demo DOCUMENTATION block

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/20231114-ansible-version.yml
changelogs/fragments/organize_github_actions.yaml
galaxy.yml

Prep cloud.common 3.0.0 release
several

Prep cloud.common 3.0.0 release

---

changelogs/fragments/20240103-module_utils-turbo-server-import-fix.yaml.yaml
plugins/module_utils/turbo/server.py

Fixes a bug where one import statement was outside the try/except block in the turbo server run_as_lookup_plugin() function. Because this is run in an async loop inside a subprocess, unhandled exceptions can cause strange behavior so it's better to have all the import statements in a try/except block that returns error messages to the user.
module_utils.turbo.server

Move turbo server import statements into try/except block

---

CI.md
README.md

The PR has been issued against the wrong branch.
Reverts ansible-collections/cloud.common#152
The PR has been re-opened against the stable-4 branch this time https://github.com/ansible-collections/cloud.common/pull/155

Revert "Update docs links after branching stable-4"

---

changelogs/fragments/168-python-312-async-support.yml
plugins/module_utils/turbo/server.py

Update how the async loop is created to support python 3.12+. In these versions of python, accessing the default loop is deprecated and you must create your own
Fixes https://github.com/ansible-collections/cloud.common/issues/164
plugins/module_utils/turbo/server

update async loop creation for python 3.12 and higher
